#!/usr/bin/env python3
"""Import 墨庐 workbench HTML/CSS/JS into the DSH plugin as scoped shadow assets."""
from __future__ import annotations

import json
import re
from pathlib import Path

SRC = Path("/Users/lijixiang/Downloads/novel-workbench")
DST = Path("/Users/lijixiang/projects/dsh-harness/novel-studio/src/client/molu")


def transform_css(css: str) -> str:
    css = re.sub(r":root\b", ":host", css)
    css = re.sub(r"html,\s*body", ":host", css)
    css = re.sub(r"(?<![\w-])body(?![\w-])", ":host", css)
    css = css.replace(
        "* { margin: 0; padding: 0; box-sizing: border-box; }",
        ":host, :host * { margin: 0; padding: 0; box-sizing: border-box; }",
    )
    css = css.replace(
        '[data-theme="light"] {',
        ':host([data-theme="light"]), [data-theme="light"] {',
    )
    css = css.replace(
        '[data-theme="dark"] {',
        ':host([data-theme="dark"]), [data-theme="dark"] {',
    )
    extra = """
:host {
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
  min-height: 0;
  min-width: 0;
  overflow: hidden;
  font-family: var(--serif);
}
:host .app,
:host .view-library {
  width: 100%;
}
"""
    return extra + css


def extract_html(raw: str) -> str:
    body = re.search(r"<body[^>]*>(.*)</body>", raw, re.S)
    if not body:
        raise SystemExit("no body in index.html")
    html = body.group(1)
    html = re.sub(r"<script[\s\S]*?</script>", "", html)
    html = html.replace("本地文档库", "Harness 书库")
    html = html.replace("原型演示 · 设置", "插件设置见 Harness 设置页")
    return html.strip()


def wrap_app(src: str) -> str:
    src = src.replace("'use strict';", "")
    start = src.find("const $  =")
    boot = src.find("document.addEventListener('DOMContentLoaded'")
    if start < 0 or boot < 0:
        raise SystemExit("unexpected app.js shape")
    prefix = src[start:boot]
    # Drop original $ helpers; we inject scoped ones.
    prefix = re.sub(
        r"const \$  = \(s, el\) => \(el \|\| document\)\.querySelector\(s\);\n"
        r"const \$\$ = \(s, el\) => Array\.from\(\(el \|\| document\)\.querySelectorAll\(s\)\);\n+",
        "",
        prefix,
        count=1,
    )
    prefix = prefix.replace("document.body.classList", "root.classList")
    prefix = prefix.replace("document.documentElement", "root")
    # Empty library is valid inside the plugin (no sample BOOKS).
    prefix = prefix.replace(
        "if (!Array.isArray(list) || !list.length) return null;",
        "if (!Array.isArray(list)) return null;\n  if (!list.length) return [];",
    )
    # Skip IndexedDB follow-up; the host already gave us the full snapshot.
    prefix = re.sub(
        r"/\* localStorage[\s\S]*?\.catch\(\(\) => \{\}\);",
        "/* async follow-up disabled: host snapshot is authoritative */",
        prefix,
        count=1,
    )

    inner = src[boot:]
    inner = inner.replace("document.body.classList", "root.classList")
    inner = inner.replace("document.documentElement", "root")
    inner = inner.replace(
        "document.addEventListener('keydown'",
        "root.addEventListener('keydown'",
    )
    inner = inner.replace(
        "document.activeElement",
        "(shadow.activeElement || document.activeElement)",
    )
    inner = inner.replace(
        "$('#settingsBtn').onclick = () => toast('原型演示 · 设置');",
        "$('#settingsBtn').onclick = () => toast('书库目录在 Harness 设置 · 小说创作台');",
    )
    inner = inner.replace(
        "window.addEventListener('beforeunload', flush);",
        "window.addEventListener('beforeunload', flush);\n  cleanups.push(() => window.removeEventListener('beforeunload', flush));",
    )
    # Extract callback body.
    brace = inner.find("{")
    body = inner[brace + 1 :]
    # Drop trailing `});` of addEventListener
    body = re.sub(r"\s*\}\);\s*$", "\n", body)

    return f"""/* generated by scripts/import-molu.py — do not edit by hand */
export function bootMoluApp(host, hostStore) {{
  const root = host;
  const shadow = host.shadowRoot;
  const document = host.ownerDocument;
  const window = document.defaultView;
  const $  = (s, el) => (el || shadow).querySelector(s);
  const $$ = (s, el) => Array.from((el || shadow).querySelectorAll(s));
  const ML_STORE = hostStore;
  const BOOKS = [];
  let DATA = null;
  let disposed = false;
  const cleanups = [];

{prefix}
{body}

  return function disposeMoluApp() {{
    if (disposed) return;
    disposed = true;
    for (const stop of cleanups) {{
      try {{ stop(); }} catch (_) {{}}
    }}
  }};
}}
"""


def write_ts_const(path: Path, name: str, value: str) -> None:
    path.write_text(
        f"/* generated by scripts/import-molu.py — do not edit by hand */\n"
        f"export const {name}: string = {json.dumps(value)};\n",
        encoding="utf-8",
    )


def main() -> None:
    DST.mkdir(parents=True, exist_ok=True)
    css = transform_css((SRC / "css/styles.css").read_text(encoding="utf-8"))
    html = extract_html((SRC / "index.html").read_text(encoding="utf-8"))
    runtime = wrap_app((SRC / "js/app.js").read_text(encoding="utf-8"))
    write_ts_const(DST / "styles.ts", "MOLU_CSS", css)
    write_ts_const(DST / "markup.ts", "MOLU_HTML", html)
    (DST / "runtime.js").write_text(runtime, encoding="utf-8")
    print(f"wrote {DST / 'styles.ts'} ({len(css)} css chars)")
    print(f"wrote {DST / 'markup.ts'} ({len(html)} html chars)")
    print(f"wrote {DST / 'runtime.js'} ({runtime.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
